name: setup-test-lint
# on – определяет события, которые запускают воркфлоу
on: push
jobs:
  # build – произвольно выбранное имя задания
  # их может быть больше одного
  setup-test-lint:
    # операционная система для работы воркфлоу
    runs-on: ubuntu-latest
    steps: # список шагов, которые надо выполнить
      # экшен — выполняет какую-то задачу
      # checkout — клонирует репозиторий
      - uses: actions/checkout@v4
      # ставит node.js
      - uses: actions/setup-node@v4
      # run – произвольная bash-команда
      - uses: hexlet-components/hello-from-hexlet-action@release
      - run: make install
      - run: make setup
      - run: make test
      - run: make lint